### ISSUE TITLE
Faire fonctionner la documentation swagger pour l'api v2

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#607]
Actuellement, la documentation swagger de l'api v2 (http://dev.local:7000/api/2/) ne fonctionne pas car on utilise des modèles définis uniquement dans l'api v1.

Une proposition de solution pourrait de tirer parti des inherit (voir https://github.com/maudetes/udata/commit/9b133f6e6eb1f4a53c9e27fed52369b430f86b6f).

**Comment by abulte** [comment]
Seems fine as a "quick fix", but maybe we should look into upping our standards re API documentation, by using openapi instead of the deprecated swagger for example. This would lead the way to getting rid of the (deprecated 😅)  `Flask-Restplus`. But it can come later.

Also, the inheritance documents only the API v2 endpoints and not the v1 ones, right (this is what we want IMHO)?

**Comment by maudetes** [comment]
> Also, the inheritance documents only the API v2 endpoints and not the v1 ones, right (this is what we want IMHO)?

Yep, it looks like this:
![image](https://user-images.githubusercontent.com/28541902/140485075-2cb24c1f-ac8e-4978-9010-caee841cd4a2.png)
